`use client`

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className=" bg-gradient-to-br from-green-700 via-lime-600 to-lime-300 h-full flex flex-col">
      <body>{children}</body>
    </html>
  )
}