`use client`
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className=" bg-gradient-to-br from-green-700 via-lime-600 to-lime-300 h-full flex flex-col">
      {/* <span className="flex flex-row justify-center items-start w-full text-center bg-gradient-to-b from-neutral-100 via-neutral-200 to-neutral-400 shadow-sm shadow-gray-400">
        <div className="m-auto">
          <p>Menu</p>
        </div>
        <div className="m-auto">
          <p>Bills</p>
        </div>
        <div className="m-auto">
          <p>Account</p>
        </div>
      </span> */}
      <body>{children}</body>
      {/* <span className="flex flex-row justify-center items-end w-full text-center bg-gradient-to-b from-neutral-100 via-neutral-200 to-neutral-400 shadow-sm shadow-gray-400">
        <div>
          <p>Footer data</p>
        </div>
      </span> */}
    </html>
  )
}
