export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className=" bg-gradient-to-br from-green-700 via-lime-800 to-lime-300">
      <body className="">{children}</body>
    </html>
  )
}
