import "../styles/globals.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className=" bg-gradient-to-br from-green-900 via-lime-700 to-lime-500 h-screen">
      <body>{children}</body>
    </html>
  )
}
